### ISSUE TITLE
Don't hard-code upstream DNS resolvers

### ISSUE THREAD

**Issue by blalor** [home-assistant/plugin-dns#53]
Applications should not hard-code their own DNS resolvers; they should use the configuration provided by the network (via DHCP) or by the user, perhaps with an overridable default if no other option exists.  This is an anti-pattern:
https://github.com/home-assistant/plugin-dns/blob/be7b7e7fc4460ef31483882e743ba4e3b62fe8c4/rootfs/usr/share/tempio/corefile#L30

**Comment by frenck** [comment]
This has been discussed in various places in the past.

<https://github.com/home-assistant/plugin-dns/issues/22#issuecomment-769916961>

The project is not changing this.

**Comment by vistalba** [comment]
Would it be possible to make it configurable so that advanced users could disable this behavior?
I do not want to start a fundamental discussion, as I read a lot and I see that there are two or more views to this point.

But what is the technical reason not doing so?
I'm happy to support with that but unfortunately I do not have any experience in coding so I'm not able to raise a pull request.

Maybe some config in `customize.yaml` like:

```
dns-fallback: false
```

or

```
dns-fallback: true
dns-fallback-servers: tls://8.8.8.8
```
