### ISSUE TITLE
.mydomain.local domain names no longer work

### ISSUE THREAD

**Issue by mrgfisher** [home-assistant/plugin-dns#93]
Hi,

I've seen other (now closed) bugs that .local is no longer a supported thing. However, the change stops integrations to synology, camera, the recorder etc where they have names such as recorder.mydomain.local

For now, I've reverted to an earlier build (thank goodness for snapshots).

Naturally I used a DNS on my local network that handles the 'mydomain.local'. 

Is it 'desired' that the change https://github.com/home-assistant/plugin-dns/commit/8e0ea74e46bd85579948b0e3b1e0bbad35bbacc7 stops any form of forwarding? 

Apols if I'm reading the commit wrong, or if having a 'mydomain.local' is a bad thing, or if I've missed somethin in release notes - I do read them and am a happy suscriber to casa.  If I do need to stop using .mydomain.local then its a fair amount of pain to rebuild AD domain, fixup broken (domain) devices, reconfigure a few dozen devices and finally rebuild customisation within home assistant.

**Comment by mdegat01** [comment]
`.local` is reserved for mdns. It's not a domain that DNS resolvers should be answering queries on. That's why for example if you do `dig <something>.local` you get this warning in the output:
```
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
```

And just to clarify on that PR, after #73 plugin-dns no longer resolves multicast names (single-label names or ones that end in .local) by itself. It simply hands those queries off to systemd-resolved on the host.

Systemd-resolved on the host knows mdns, llmnr and the DNS server(s) you see in `locals` when you run `ha dns info`. It can use any and all of that information to resolve queries. It doesn't use the last part though for the same reason `dig` gives that output, you aren't supposed to forward multicast names to DNS resolvers (see [here](https://github.com/systemd/systemd/blob/2afb2f4a9d6a497dfbe1983fbe1bac297a8dc52b/src/resolve/resolved-dns-scope.c#L797-L813) for the systemd-resolved code that handles this).

So yea I'm sorry for the inconvenience here but if you were relying on your DNS server giving answers for `.local` queries then you're going to need to switch to a different internal TLD like `.lan` or `.home.arpa`. Something that isn't reserved for multicast queries in [the spec](https://www.rfc-editor.org/rfc/rfc6762.html). Or if you prefer you can switch to a container install as then you can take greater control over the network settings and do what you wish with `.local`.

**Comment by mrgfisher** [comment]
Thanks @mdegat01 for the reply and detail. I wasn't aware that .local as a TLD is reserved / restricted in its application. Unfortunately my 'local' domain and setup with Active Directory uses something like .mydomain.local 

Closing the ticket.
